# Generated by Django 2.2 on 2020-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_photo', models.ImageField(upload_to='passports/')),
                ('image_registration', models.ImageField(upload_to='passports/')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('serial_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('place_of_birth', models.TextField()),
                ('issue_date', models.DateField()),
                ('department_code', models.IntegerField()),
                ('issued_by', models.TextField()),
                ('registration_adress', models.TextField(max_length=300)),
            ],
        ),
    ]
