# Generated by Django 2.2 on 2020-10-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'New'), ('1', 'identification'), ('2', 'regulations'), ('CF', 'conformation'), ('DE', 'denial')], default='NW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='documents/')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='api.Qualification')),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='qualification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='api.Qualification'),
            preserve_default=False,
        ),
    ]
