# Generated by Django 2.2 on 2020-10-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201024_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='rule_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='rule_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='rule_two',
            field=models.BooleanField(default=False),
        ),
    ]
