# Generated by Django 2.2 on 2020-10-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201025_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='qualification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='api.Qualification'),
        ),
    ]
